### ISSUE TITLE
Improve UI along with Dark/Light theme toggle.

### ISSUE THREAD

**Issue by Aniumbott** [Aniumbott/Todo-List#1]
This website is working properly, but looks too simple. I think it looks good and flexible if it has a theme toggle and an attractive UI. (Open for the suggestions and ideas.)

- Create a separate branch other from main.
- Please attach a Screenshot of the page in the PR.
- Don't forget to star this repo and follow. 😇

**Comment by archish99** [comment]
Hey, I see that you have created a javascript app. Can we convert this into a react app and improve the UI along the way? Working together?

**Comment by Aniumbott** [comment]
I'm still learning react so not enough idea, but if you can, sure go ahead but don't delete the JS file. 😅

**Comment by garimavs** [comment]
I would like to add a navbar and a footer to it. Would you mind assigning it to me?

**Comment by Aniumbott** [comment]
Its just a simple Todo list so not required though. 😅

**Comment by Aniumbott** [comment]
@archish99 had any queries or issues you are facing ?
And it is completely ok if you don't want to work on it 😅

**Comment by garimavs** [comment]
Thanks, @Aniumbott, for assigning it to me. I will indeed look at it.
